<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="23.6.2" />
    <PackageReference Include="PDFiumCore" Version="147.0.7699" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
  </ItemGroup>

</Project>
